name: Generate a new json from az-cli

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

permissions:
    contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_RBAC_READ_CREDENTIALS }}
        
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Azure CLI script file
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            chmod +x $GITHUB_WORKSPACE/generate-json.sh
            $GITHUB_WORKSPACE/generate-json.sh

      - name: Commit and push if changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit -am "Automated update of JSONs from az-cli"
          git push

